services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=TodoApp
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: